[build]
builder = "nixpacks"

[deploy]
startCommand = "pip install -r requirements.txt && python deploy.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "web"
source = "."

[[services]]
name = "worker"
source = "."
command = "python background_price_worker.py"