[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --settings=delivery_tracker.settings_production && python manage.py collectstatic --noinput --settings=delivery_tracker.settings_production && gunicorn delivery_tracker.wsgi:application --bind 0.0.0.0:$PORT --env DJANGO_SETTINGS_MODULE=delivery_tracker.settings_production"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
source = "."

[services.build]
builder = "nixpacks"

[services.deploy]
startCommand = "python manage.py migrate --settings=delivery_tracker.settings_production && python manage.py collectstatic --noinput --settings=delivery_tracker.settings_production && gunicorn delivery_tracker.wsgi:application --bind 0.0.0.0:$PORT --env DJANGO_SETTINGS_MODULE=delivery_tracker.settings_production"

[[services]]
name = "price-service"
source = "."

[services.build]
builder = "nixpacks"

[services.deploy]
startCommand = "python RAILWAY_STARTUP_FIX.py"
