[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn delivery_tracker.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
