# Generated by Django 4.2.7 on 2025-08-30 23:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-chart-line', max_length=50)),
                ('color', models.CharField(default='#1e40af', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Investment Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('current_price_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('price_change_24h', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_change_percentage_24h', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('purity', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('investment_type', models.CharField(choices=[('investment_only', 'Investment Only'), ('delivery_only', 'Delivery Only'), ('both', 'Investment & Delivery')], default='both', max_length=20)),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('maximum_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_available', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('currently_available', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='investment_items/')),
                ('additional_images', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='investments.investmentcategory')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('purchase_price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_return_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_return_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('investment_type', models.CharField(choices=[('hold', 'Hold for Investment'), ('delivery', 'Buy for Delivery')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investments', to='investments.investmentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Investments',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='investments.investmentitem')),
            ],
            options={
                'verbose_name_plural': 'Price History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('delivery', 'Delivery'), ('refund', 'Refund')], max_length=20)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='nowpayments', max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('nowpayments_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('nowpayments_payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('crypto_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.userinvestment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investmentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Investment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_return', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_return_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('active_investments_count', models.PositiveIntegerField(default=0)),
                ('total_investments_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Investment Portfolios',
            },
        ),
    ]
