# Generated by Django 4.2.7 on 2025-08-31 20:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimePriceFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('palladium', 'Palladium'), ('diamond', 'Diamond'), ('crypto', 'Cryptocurrency'), ('real_estate', 'Real Estate'), ('art', 'Art'), ('other', 'Other')], max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('base_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], default='USD', max_length=3)),
                ('price_change_24h', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('price_change_percentage_24h', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_change_7d', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('price_change_percentage_7d', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('api_source', models.CharField(blank=True, max_length=100)),
                ('api_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Real Time Price Feeds',
                'ordering': ['asset_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RealTimePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('change_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='investments.realtimepricefeed')),
            ],
            options={
                'verbose_name_plural': 'Real Time Price History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCashoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('requested_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], default='USD', max_length=3)),
                ('bank_account_details', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cashouts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Cashout Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=3)),
                ('to_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('api_source', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currency Conversions',
                'ordering': ['from_currency', 'to_currency'],
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
        migrations.CreateModel(
            name='AutoInvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('next_investment_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('investments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_investment_at', models.DateTimeField(blank=True, null=True)),
                ('target_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_investment_plans', to='investments.investmentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_investment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Auto Investment Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
