# Generated by Django 4.2.7 on 2025-09-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_realtimepricefeed_realtimepricehistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentitem',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='investmentitem',
            name='main_image',
        ),
        migrations.AddField(
            model_name='investmentitem',
            name='additional_image_urls',
            field=models.JSONField(blank=True, default=list, help_text='Enter URLs of additional images as a list'),
        ),
        migrations.AddField(
            model_name='investmentitem',
            name='main_image_url',
            field=models.URLField(blank=True, help_text='Enter the URL of the main image', max_length=500, null=True),
        ),
    ]
