# Generated by Django 4.2.7 on 2025-09-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_remove_investmentitem_additional_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentitem',
            name='symbol',
            field=models.CharField(blank=True, help_text='Symbol for live price updates (e.g., BTC, ETH, XAU)', max_length=20, null=True),
        ),
    ]
