# Generated by Django 4.2.7 on 2025-09-02 03:30:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_investmentitem_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentitem',
            name='last_price_update',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Last time the price was updated'),
            preserve_default=False,
        ),
    ]
