# Generated by Django 4.2.7 on 2025-09-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_paymenttransaction_membershippayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='payment_address',
            field=models.CharField(blank=True, help_text='NOWPayments payment address', max_length=255, null=True),
        ),
    ]
