# Generated by Django 4.2.7 on 2025-09-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_investmenttransaction_payment_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMovementStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increases_today', models.PositiveIntegerField(default=0)),
                ('decreases_today', models.PositiveIntegerField(default=0)),
                ('unchanged_today', models.PositiveIntegerField(default=0)),
                ('increases_this_week', models.PositiveIntegerField(default=0)),
                ('decreases_this_week', models.PositiveIntegerField(default=0)),
                ('unchanged_this_week', models.PositiveIntegerField(default=0)),
                ('increases_this_month', models.PositiveIntegerField(default=0)),
                ('decreases_this_month', models.PositiveIntegerField(default=0)),
                ('unchanged_this_month', models.PositiveIntegerField(default=0)),
                ('highest_price_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lowest_price_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_price_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Price Movement Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='movement_type',
            field=models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('unchanged', 'Unchanged')], default='unchanged', max_length=10),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='volume_24h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['item', 'timestamp'], name='investments_item_id_8e1057_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['timestamp'], name='investments_timesta_fc4c06_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['movement_type'], name='investments_movemen_eb9fab_idx'),
        ),
        migrations.AddField(
            model_name='pricemovementstats',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_stats', to='investments.investmentitem'),
        ),
        migrations.AlterUniqueTogether(
            name='pricemovementstats',
            unique_together={('item', 'date')},
        ),
    ]
