# Generated by Django 4.2.7 on 2025-09-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_pricemovementstats_pricehistory_market_cap_and_more'),
    ]

    operations = [
    ]
