# Generated by Django 4.2.7 on 2025-09-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_newscache_newscategory_newssource_usernewspreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentitem',
            name='price_change_percentage_24h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='change_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
