# Generated by Django 4.2.7 on 2025-09-15 03:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_fix_price_percentage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('crypto_currency', models.CharField(default='BTC', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('fast', 'Fast Track'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, help_text='Estimated delivery date', null=True)),
                ('payment_id', models.CharField(blank=True, help_text='NOWPayments transaction ID', max_length=100)),
                ('payment_address', models.CharField(blank=True, help_text='Crypto address for payment', max_length=200)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=8, help_text='Amount in crypto', max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('is_public', models.BooleanField(default=True, help_text='Show in public withdrawal list')),
                ('order_position', models.PositiveIntegerField(default=0, help_text='Position in the list (0 = top)')),
            ],
            options={
                'verbose_name': 'Crypto Withdrawal',
                'verbose_name_plural': 'Crypto Withdrawals',
                'ordering': ['order_position', '-created_at'],
            },
        ),
    ]
