# Generated by Django 4.2.7 on 2025-09-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_cryptowithdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowithdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('halted', 'Halted')], default='pending', max_length=20),
        ),
    ]
