# Generated by Django 4.2.7 on 2025-09-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_add_halted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=501),
        ),
    ]
