# Generated by Django 4.2.7 on 2025-09-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_fix_title_length_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
