# Generated by Django 4.2.7 on 2025-10-11 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_fix_duplicate_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(help_text='Unique VIP member identifier', max_length=20, unique=True)),
                ('membership_tier', models.CharField(choices=[('bronze', 'Bronze VIP'), ('silver', 'Silver VIP'), ('gold', 'Gold VIP'), ('platinum', 'Platinum VIP'), ('diamond', 'Diamond VIP')], default='bronze', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], default='email', max_length=20)),
                ('priority_support', models.BooleanField(default=True)),
                ('dedicated_account_manager', models.BooleanField(default=True)),
                ('exclusive_investment_opportunities', models.BooleanField(default=True)),
                ('faster_processing', models.BooleanField(default=True)),
                ('total_investments', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_worth', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('membership_start_date', models.DateTimeField(auto_now_add=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the VIP member', null=True)),
                ('assigned_staff', models.ForeignKey(blank=True, help_text='VIP Staff member assigned to this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vip_members', to='accounts.staffprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VIP Profile',
                'verbose_name_plural': 'VIP Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
