# Generated by Django 4.2.7 on 2025-10-13 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vipprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('investment_return', 'Investment Return'), ('wire_transfer', 'International Wire Transfer'), ('dividend_payment', 'Dividend Payment'), ('service_fee', 'Service Fee'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('loan_payment', 'Loan Payment'), ('interest_payment', 'Interest Payment'), ('refund', 'Refund'), ('commission', 'Commission'), ('bonus', 'Bonus'), ('penalty', 'Penalty'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(help_text='Display title for the activity', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the activity', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (positive for incoming, negative for outgoing)', max_digits=15)),
                ('currency', models.CharField(default='USD', help_text='Currency code (USD, EUR, etc.)', max_length=3)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], help_text='Whether this is an incoming or outgoing transaction', max_length=10)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('processing', 'Processing')], default='completed', max_length=20)),
                ('activity_date', models.DateTimeField(help_text='When this activity occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this activity', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying activities (higher numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this activity should be displayed')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this activity should be highlighted')),
                ('vip_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to='accounts.vipprofile')),
            ],
            options={
                'verbose_name': 'Recent Activity',
                'verbose_name_plural': 'Recent Activities',
                'ordering': ['-display_order', '-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['vip_member', '-activity_date'], name='accounts_re_vip_mem_4021b0_idx'), models.Index(fields=['status', '-activity_date'], name='accounts_re_status_17b3d4_idx'), models.Index(fields=['is_active', '-activity_date'], name='accounts_re_is_acti_a9953e_idx')],
            },
        ),
    ]
