# Generated by Django 4.2.7 on 2025-10-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_recentactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=15)),
                ('currency', models.CharField(default='USD', help_text='Currency code (USD, EUR, etc.)', max_length=3)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('investment', 'Investment'), ('loan', 'Loan'), ('payment', 'Payment'), ('refund', 'Refund'), ('fee', 'Fee'), ('interest', 'Interest'), ('dividend', 'Dividend'), ('bonus', 'Bonus'), ('commission', 'Commission'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('scope', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('international', 'International'), ('local', 'Local')], default='internal', max_length=20)),
                ('reference_id', models.CharField(help_text='Unique transaction reference ID', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Transaction description')),
                ('transaction_date', models.DateTimeField(help_text='When the transaction occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this transaction', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional transaction metadata', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this transaction should be displayed')),
                ('vip_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.vipprofile')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['vip_member', '-transaction_date'], name='accounts_tr_vip_mem_ea3ace_idx'), models.Index(fields=['status', '-transaction_date'], name='accounts_tr_status_5c286a_idx'), models.Index(fields=['transaction_type', '-transaction_date'], name='accounts_tr_transac_c97aaa_idx'), models.Index(fields=['reference_id'], name='accounts_tr_referen_abf5ff_idx')],
            },
        ),
    ]
