# Generated by Django 4.2.7 on 2025-10-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Masked card number (e.g., **** **** **** 1234)', max_length=19)),
                ('card_type', models.CharField(choices=[('virtual', 'Virtual Card'), ('physical', 'Physical Card'), ('prepaid', 'Prepaid Card'), ('debit', 'Debit Card'), ('credit', 'Credit Card')], default='virtual', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('card_name', models.CharField(help_text='Name on the card', max_length=100)),
                ('expiry_month', models.CharField(help_text='Expiry month (01-12)', max_length=2)),
                ('expiry_year', models.CharField(help_text='Expiry year (YYYY)', max_length=4)),
                ('spending_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly spending limit', max_digits=15, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current card balance', max_digits=15)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('issue_date', models.DateTimeField(auto_now_add=True, help_text='When the card was issued')),
                ('expiry_date', models.DateTimeField(help_text='When the card expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Card description or purpose', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this card', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this card should be displayed')),
                ('vip_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.vipprofile')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vip_member', '-created_at'], name='accounts_ca_vip_mem_bc2f20_idx'), models.Index(fields=['status', '-created_at'], name='accounts_ca_status_06209b_idx'), models.Index(fields=['card_type', '-created_at'], name='accounts_ca_card_ty_7eaf88_idx')],
            },
        ),
    ]
