# Generated by Django 4.2.7 on 2025-10-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Card issuance fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='card',
            name='billing_address',
            field=models.TextField(blank=True, help_text='Billing address for verification', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_brand',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express')], default='visa', help_text='Card brand (Visa, Mastercard, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='card_level',
            field=models.CharField(choices=[('standard', 'Standard - $5.00'), ('gold', 'Gold - $15.00'), ('platinum', 'Platinum - $25.00'), ('black', 'Black - $50.00')], default='standard', help_text='Card level with associated fee', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(blank=True, help_text='Name as it will appear on the card', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='daily_spending_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily spending limit', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='User accepted terms and conditions'),
        ),
        migrations.AlterField(
            model_name='card',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound')], default='USD', help_text='Currency code', max_length=3),
        ),
    ]
