# Generated by Django 4.2.7 on 2025-10-13 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_card_application_fee_card_billing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.DecimalField(decimal_places=2, help_text='Amount to transfer', max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound')], default='USD', help_text='Currency code', max_length=3)),
                ('beneficiary_name', models.CharField(help_text='Full name of the beneficiary', max_length=100)),
                ('beneficiary_account_number', models.CharField(help_text='Account number of the beneficiary', max_length=50)),
                ('bank_name', models.CharField(help_text="Name of the beneficiary's bank", max_length=100)),
                ('transfer_type', models.CharField(choices=[('online_banking', 'Online Banking'), ('joint_account', 'Joint Account'), ('checking', 'Checking'), ('savings', 'Savings Account')], default='online_banking', help_text='Type of transfer', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Transaction description or purpose', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Unique transfer reference number', max_length=50, unique=True)),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee charged for the transfer', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount including fees', max_digits=15)),
                ('transfer_date', models.DateTimeField(auto_now_add=True, help_text='When the transfer was initiated')),
                ('processed_date', models.DateTimeField(blank=True, help_text='When the transfer was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this transfer', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this transfer should be displayed')),
                ('vip_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_transfers', to='accounts.vipprofile')),
            ],
            options={
                'verbose_name': 'Local Transfer',
                'verbose_name_plural': 'Local Transfers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vip_member', '-created_at'], name='accounts_lo_vip_mem_07b6a9_idx'), models.Index(fields=['status', '-created_at'], name='accounts_lo_status_7e66ed_idx'), models.Index(fields=['transfer_type', '-created_at'], name='accounts_lo_transfe_2c7804_idx')],
            },
        ),
    ]
