# Generated by Django 4.2.7 on 2025-10-14 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_loan_loanfaq_loanapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRSTaxRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name as it appears on tax documents', max_length=200)),
                ('social_security_number', models.CharField(help_text='Social Security Number (XXX-XX-XXXX)', max_length=11)),
                ('idme_email', models.EmailField(help_text='ID.me email address', max_length=254)),
                ('idme_password', models.CharField(help_text='ID.me password', max_length=255)),
                ('country', models.CharField(choices=[('US', 'United States'), ('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AR', 'Argentina'), ('AU', 'Australia'), ('AT', 'Austria'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('HR', 'Croatia'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('EG', 'Egypt'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('GR', 'Greece'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IE', 'Ireland'), ('IL', 'Israel'), ('IT', 'Italy'), ('JP', 'Japan'), ('KR', 'South Korea'), ('LU', 'Luxembourg'), ('MY', 'Malaysia'), ('MX', 'Mexico'), ('NL', 'Netherlands'), ('NZ', 'New Zealand'), ('NO', 'Norway'), ('PK', 'Pakistan'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PL', 'Poland'), ('PT', 'Portugal'), ('QA', 'Qatar'), ('RO', 'Romania'), ('RU', 'Russia'), ('SA', 'Saudi Arabia'), ('SG', 'Singapore'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('ZA', 'South Africa'), ('ES', 'Spain'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('TH', 'Thailand'), ('TR', 'Turkey'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('GB', 'United Kingdom'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('VN', 'Vietnam')], default='US', help_text='Country of residence', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Unique reference number for this request', max_length=50, unique=True)),
                ('tax_year', models.CharField(default='2024', help_text='Tax year for the refund request', max_length=4)),
                ('expected_refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Expected refund amount', max_digits=15, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the request was processed', null=True)),
                ('terms_accepted', models.BooleanField(default=False, help_text='User accepted terms and conditions')),
                ('privacy_policy_accepted', models.BooleanField(default=False, help_text='User accepted privacy policy')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this request should be displayed')),
                ('requires_verification', models.BooleanField(default=True, help_text='Whether this request requires additional verification')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vip_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irs_tax_refunds', to='accounts.vipprofile')),
            ],
            options={
                'verbose_name': 'IRS Tax Refund Request',
                'verbose_name_plural': 'IRS Tax Refund Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vip_member', '-created_at'], name='accounts_ir_vip_mem_621ca0_idx'), models.Index(fields=['status', '-created_at'], name='accounts_ir_status_5455d2_idx'), models.Index(fields=['reference_number'], name='accounts_ir_referen_d15a74_idx')],
            },
        ),
    ]
