# Generated by Django 4.2.7 on 2025-10-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_irstaxrefund'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('home', 'Home Loan'), ('car', 'Car Loan'), ('education', 'Education Loan'), ('emergency', 'Emergency Loan'), ('investment', 'Investment Loan')], help_text='Type of loan applied for', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Loan amount requested', max_digits=15)),
                ('purpose', models.CharField(choices=[('debt_consolidation', 'Debt Consolidation'), ('home_improvement', 'Home Improvement'), ('business_expansion', 'Business Expansion'), ('education', 'Education'), ('medical', 'Medical Expenses'), ('wedding', 'Wedding'), ('vacation', 'Vacation'), ('emergency', 'Emergency'), ('investment', 'Investment'), ('other', 'Other')], help_text='Purpose of the loan', max_length=30)),
                ('duration_months', models.IntegerField(choices=[(6, '6 Months'), (12, '1 Year'), (18, '18 Months'), (24, '2 Years'), (36, '3 Years'), (48, '4 Years'), (60, '5 Years'), (84, '7 Years'), (120, '10 Years')], help_text='Loan duration in months')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Unique reference number for this loan application', max_length=50, unique=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate (if approved)', max_digits=5, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly payment amount (if approved)', max_digits=15, null=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', null=True)),
                ('vip_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_history', to='accounts.vipprofile')),
            ],
            options={
                'verbose_name': 'Loan History Entry',
                'verbose_name_plural': 'Loan History Entries',
                'ordering': ['-date_applied'],
            },
        ),
    ]
