# Generated by Django 4.2.7 on 2025-10-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_loanhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=100)),
                ('last_name', models.CharField(help_text='Last name', max_length=100)),
                ('email', models.EmailField(help_text='Primary email address', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number with country code', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('address', models.TextField(blank=True, help_text='Full address')),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=100)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ar', 'Arabic')], default='en', help_text='Preferred language', max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan')], default='USD', help_text='Preferred currency', max_length=3)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone', max_length=50)),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Two-factor authentication enabled')),
                ('email_notifications', models.BooleanField(default=True, help_text='Email notifications enabled')),
                ('sms_notifications', models.BooleanField(default=False, help_text='SMS notifications enabled')),
                ('push_notifications', models.BooleanField(default=True, help_text='Push notifications enabled')),
                ('transaction_pin', models.CharField(blank=True, help_text='Transaction PIN (encrypted)', max_length=6)),
                ('daily_transaction_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Daily transaction limit', max_digits=15, null=True)),
                ('monthly_transaction_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly transaction limit', max_digits=15, null=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='private', help_text='Profile visibility', max_length=20)),
                ('data_sharing', models.BooleanField(default=False, help_text='Allow data sharing for analytics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profile_pictures/')),
                ('vip_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to='accounts.vipprofile')),
            ],
            options={
                'verbose_name': 'Account Settings',
                'verbose_name_plural': 'Account Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
