# Generated by Django 4.2.7 on 2025-10-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_accountsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief description of the issue', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='low', help_text='Priority level of the ticket', max_length=10)),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Issue'), ('account', 'Account Issue'), ('billing', 'Billing Question'), ('transaction', 'Transaction Problem'), ('security', 'Security Concern'), ('feature_request', 'Feature Request'), ('other', 'Other')], default='general', help_text='Category of the issue', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting for Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current status of the ticket', max_length=20)),
                ('ticket_number', models.CharField(blank=True, help_text='Unique ticket number', max_length=20, unique=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='File attachments (stored as JSON)')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_at', models.DateTimeField(blank=True, null=True)),
                ('response_count', models.PositiveIntegerField(default=0, help_text='Number of responses')),
                ('vip_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='accounts.vipprofile')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
