# Generated by Django 4.2.7 on 2025-10-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPFinancialMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current account balance', max_digits=15)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Available balance for transactions', max_digits=15)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Pending transactions balance', max_digits=15)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly income amount', max_digits=15)),
                ('monthly_outgoing', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly outgoing transactions', max_digits=15)),
                ('monthly_savings', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly savings amount', max_digits=15)),
                ('total_investments', models.DecimalField(decimal_places=2, default=0.0, help_text='Total investment amount', max_digits=15)),
                ('net_worth', models.DecimalField(decimal_places=2, default=100000.0, help_text='Total net worth', max_digits=15)),
                ('investment_growth', models.DecimalField(decimal_places=2, default=0.0, help_text='Investment growth percentage', max_digits=10)),
                ('transaction_limit', models.DecimalField(decimal_places=2, default=500000.0, help_text='Daily transaction limit', max_digits=15)),
                ('monthly_transaction_limit', models.DecimalField(decimal_places=2, default=2000000.0, help_text='Monthly transaction limit', max_digits=15)),
                ('pending_transactions', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount in pending transactions', max_digits=15)),
                ('transaction_volume', models.DecimalField(decimal_places=2, default=0.0, help_text='Total transaction volume', max_digits=15)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('under_review', 'Under Review')], default='active', help_text='Account status', max_length=20)),
                ('credit_score', models.IntegerField(default=750, help_text='Credit score (300-850)')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], default='low', help_text='Risk assessment level', max_length=20)),
                ('primary_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], default='USD', help_text='Primary currency', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='Current exchange rate', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time metrics were updated')),
                ('vip_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_metrics', to='accounts.vipprofile')),
            ],
            options={
                'verbose_name': 'VIP Financial Metrics',
                'verbose_name_plural': 'VIP Financial Metrics',
                'ordering': ['-updated_at'],
            },
        ),
    ]
