# Generated by Django 4.2.7 on 2025-10-15 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_vipfinancialmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full legal name', max_length=100)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('title', models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('miss', 'Miss'), ('dr', 'Dr.'), ('prof', 'Prof.')], help_text='Title', max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=10)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('zipcode', models.CharField(help_text='Zip/Postal code', max_length=10)),
                ('ssn_number', models.CharField(help_text='Social Security Number or equivalent', max_length=50)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('checking', 'Checking Account'), ('investment', 'Investment Account'), ('business', 'Business Account')], help_text='Type of account', max_length=20)),
                ('employment_type', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student')], help_text='Type of employment', max_length=20)),
                ('annual_income_range', models.CharField(choices=[('under_25k', 'Under $25,000'), ('25k_50k', '$25,000 - $50,000'), ('50k_75k', '$50,000 - $75,000'), ('75k_100k', '$75,000 - $100,000'), ('100k_150k', '$100,000 - $150,000'), ('150k_200k', '$150,000 - $200,000'), ('over_200k', 'Over $200,000')], help_text='Annual income range', max_length=20)),
                ('address_line', models.TextField(help_text='Street address')),
                ('city', models.CharField(help_text='City', max_length=50)),
                ('state', models.CharField(help_text='State/Province', max_length=50)),
                ('nationality', models.CharField(help_text='Nationality', max_length=50)),
                ('beneficiary_name', models.CharField(help_text='Beneficiary legal name', max_length=100)),
                ('beneficiary_address', models.TextField(help_text='Next of kin address')),
                ('relationship', models.CharField(help_text='Relationship to beneficiary', max_length=50)),
                ('beneficiary_age', models.PositiveIntegerField(help_text='Age of beneficiary')),
                ('document_type', models.CharField(choices=[('passport', 'International Passport'), ('national_id', 'National ID'), ('drivers_license', 'Drivers License')], help_text='Type of ID document', max_length=20)),
                ('front_document', models.FileField(blank=True, help_text='Front side of document', null=True, upload_to='kyc/documents/')),
                ('back_document', models.FileField(blank=True, help_text='Back side of document', null=True, upload_to='kyc/documents/')),
                ('passport_photo', models.FileField(blank=True, help_text='Passport photograph', null=True, upload_to='kyc/photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_documents', 'Requires Additional Documents')], default='pending', help_text='Verification status', max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Internal verification notes')),
                ('terms_accepted', models.BooleanField(default=False, help_text='Terms and conditions accepted')),
                ('terms_accepted_at', models.DateTimeField(blank=True, help_text='When terms were accepted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When KYC was submitted', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When KYC was approved', null=True)),
                ('vip_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to='accounts.vipprofile')),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
