# Generated by Django 4.2.7 on 2025-10-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_kycverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='account_type',
            field=models.CharField(blank=True, choices=[('savings', 'Savings Account'), ('checking', 'Checking Account'), ('investment', 'Investment Account'), ('business', 'Business Account')], help_text='Type of account', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='address_line',
            field=models.TextField(blank=True, help_text='Street address'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='annual_income_range',
            field=models.CharField(blank=True, choices=[('under_25k', 'Under $25,000'), ('25k_50k', '$25,000 - $50,000'), ('50k_75k', '$50,000 - $75,000'), ('75k_100k', '$75,000 - $100,000'), ('100k_150k', '$100,000 - $150,000'), ('150k_200k', '$150,000 - $200,000'), ('over_200k', 'Over $200,000')], help_text='Annual income range', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='beneficiary_address',
            field=models.TextField(blank=True, help_text='Next of kin address'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='beneficiary_age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of beneficiary', null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='beneficiary_name',
            field=models.CharField(blank=True, help_text='Beneficiary legal name', max_length=100),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_type',
            field=models.CharField(blank=True, choices=[('passport', 'International Passport'), ('national_id', 'National ID'), ('drivers_license', 'Drivers License')], help_text='Type of ID document', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student')], help_text='Type of employment', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full legal name', max_length=100),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='relationship',
            field=models.CharField(blank=True, help_text='Relationship to beneficiary', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='ssn_number',
            field=models.CharField(blank=True, help_text='Social Security Number or equivalent', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='state',
            field=models.CharField(blank=True, help_text='State/Province', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('miss', 'Miss'), ('dr', 'Dr.'), ('prof', 'Prof.')], help_text='Title', max_length=10),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='zipcode',
            field=models.CharField(blank=True, help_text='Zip/Postal code', max_length=10),
        ),
    ]
