# Generated by Django 4.2.7 on 2025-10-16 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_kycverification_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPTransferPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(help_text='Unique payment identifier', max_length=100, unique=True)),
                ('nowpayments_payment_id', models.CharField(blank=True, help_text='NOWPayments payment ID', max_length=100, null=True)),
                ('payment_address', models.CharField(blank=True, help_text='Crypto payment address', max_length=200, null=True)),
                ('amount_crypto', models.DecimalField(blank=True, decimal_places=8, help_text='Amount in cryptocurrency', max_digits=20, null=True)),
                ('crypto_currency', models.CharField(blank=True, help_text='Cryptocurrency used for payment', max_length=10, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=15)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting for Payment'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('sending', 'Sending'), ('partially_paid', 'Partially Paid'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', help_text='Payment status', max_length=20)),
                ('payment_type', models.CharField(default='transfer', help_text='Type of payment', max_length=20)),
                ('available_balance_at_payment', models.DecimalField(decimal_places=2, help_text='Available balance when payment was initiated', max_digits=15)),
                ('transfer_percentage', models.DecimalField(decimal_places=2, default=11.0, help_text='Percentage of available balance transferred', max_digits=5)),
                ('payment_url', models.URLField(blank=True, help_text='NOWPayments payment URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('vip_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_payments', to='accounts.vipprofile')),
            ],
            options={
                'verbose_name': 'VIP Transfer Payment',
                'verbose_name_plural': 'VIP Transfer Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
