# Generated by Django 4.2.7 on 2025-10-10 15:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('membership_tiers', models.CharField(help_text='Comma-separated list of membership tiers (bronze,silver,gold,platinum,diamond)', max_length=200)),
                ('icon', models.CharField(default='fas fa-star', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VIP Benefit',
                'verbose_name_plural': 'VIP Benefits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VIPMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(help_text='Unique VIP member identifier', max_length=20, unique=True)),
                ('membership_tier', models.CharField(choices=[('bronze', 'Bronze VIP'), ('silver', 'Silver VIP'), ('gold', 'Gold VIP'), ('platinum', 'Platinum VIP'), ('diamond', 'Diamond VIP')], default='bronze', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], default='email', max_length=20)),
                ('priority_support', models.BooleanField(default=True)),
                ('dedicated_account_manager', models.BooleanField(default=True)),
                ('exclusive_investment_opportunities', models.BooleanField(default=True)),
                ('faster_processing', models.BooleanField(default=True)),
                ('total_investments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_worth', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('membership_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the VIP member')),
            ],
            options={
                'verbose_name': 'VIP Member',
                'verbose_name_plural': 'VIP Members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Unique staff identifier', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(default='VIP Services', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VIP Staff Member',
                'verbose_name_plural': 'VIP Staff Members',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='VIPNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('promotion', 'Promotion')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vip_members.vipmember')),
            ],
            options={
                'verbose_name': 'VIP Notification',
                'verbose_name_plural': 'VIP Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vipmember',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='VIP Staff member assigned to this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to='vip_members.vipstaff'),
        ),
        migrations.AddField(
            model_name='vipmember',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VIPActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Dashboard Login'), ('investment', 'Investment Activity'), ('withdrawal', 'Withdrawal Request'), ('support', 'Support Contact'), ('meeting', 'Staff Meeting'), ('call', 'Phone Call'), ('email', 'Email Communication'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_important', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='vip_members.vipmember')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vip_members.vipstaff')),
            ],
            options={
                'verbose_name': 'VIP Activity',
                'verbose_name_plural': 'VIP Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
