# Generated by Django 4.2.7 on 2025-10-10 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vip_members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_info', 'Requires Additional Information')], default='pending', max_length=20)),
                ('requested_tier', models.CharField(choices=[('bronze', 'Bronze VIP'), ('silver', 'Silver VIP'), ('gold', 'Gold VIP'), ('platinum', 'Platinum VIP'), ('diamond', 'Diamond VIP')], default='bronze', max_length=20)),
                ('reason_for_application', models.TextField(help_text='Why do you want to become a VIP member?')),
                ('investment_experience', models.TextField(help_text='Describe your investment experience')),
                ('expected_monthly_investment', models.DecimalField(decimal_places=2, default=0, help_text='Expected monthly investment amount', max_digits=12)),
                ('net_worth_range', models.CharField(help_text='Estimated net worth range', max_length=50)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], default='email', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin review')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to='vip_members.vipstaff')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VIP Application',
                'verbose_name_plural': 'VIP Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
