# Generated by Django 4.2.7 on 2025-10-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip_members', '0002_vipapplication'),
    ]

    operations = [
        # This migration ensures all VIP tables are properly created
        # The actual table creation is handled by the previous migrations
        # This is just a marker to ensure Railway applies all VIP migrations
    ]
