# Generated by Django 4.2.7 on 2025-09-06 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_delivery_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='courier_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='courier_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='courier_vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='courier_vehicle_type',
            field=models.CharField(blank=True, help_text='e.g., Motorcycle, Van, Truck', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='gps_tracking_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic GPS tracking'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_gps_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='location_update_frequency',
            field=models.IntegerField(default=30, help_text='Location update frequency in seconds'),
        ),
        migrations.CreateModel(
            name='DeliveryCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_type', models.CharField(choices=[('pickup', 'Pickup'), ('warehouse', 'Warehouse'), ('hub', 'Distribution Hub'), ('transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('custom', 'Custom Location')], max_length=20)),
                ('location_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=8, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('courier_notes', models.TextField(blank=True, null=True)),
                ('customer_notified', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='tracking.delivery')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['delivery', 'timestamp'], name='tracking_de_deliver_ab8a0d_idx'), models.Index(fields=['checkpoint_type', 'timestamp'], name='tracking_de_checkpo_a0a6eb_idx')],
            },
        ),
    ]
