# Generated by Django 4.2.7 on 2025-09-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_delivery_courier_name_delivery_courier_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text="Subscriber's first name", max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text="Subscriber's last name", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscriber is active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When the subscription was created')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When the subscription was cancelled', null=True)),
                ('source', models.CharField(default='website', help_text='Source of the subscription', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the subscriber', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the subscriber', null=True)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Subscriber preferences')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='tracking_ne_email_5c88ee_idx'), models.Index(fields=['is_active', 'subscribed_at'], name='tracking_ne_is_acti_3bdf93_idx')],
            },
        ),
    ]
